import { TranslationDictionary, Member } from './types';
import { SEED_MEMBERS } from './services/seedData';

export const TRANSLATIONS: TranslationDictionary = {
  dashboard: { en: 'Dashboard', zh: '仪表盘' },
  members: { en: 'Members', zh: '会员列表' },
  addMember: { en: 'Add Member', zh: '添加会员' },
  deleteMember: { en: 'Delete', zh: '删除' },
  overview: { en: 'Overview', zh: '概览' },
  monthlyWorkouts: { en: 'Monthly Workouts', zh: '本月训练次数' },
  maxWeight: { en: 'Max Weight (PR)', zh: '最大重量突破' },
  totalVolume: { en: 'Total Volume', zh: '总训练容量' },
  logWorkout: { en: 'Log Workout Session', zh: '记录训练' },
  exercise: { en: 'Exercise', zh: '动作' },
  weight: { en: 'Weight', zh: '重量' },
  sets: { en: 'Sets', zh: '组' },
  reps: { en: 'Reps', zh: '次' },
  addLog: { en: 'Add to Session', zh: '加入训练单' },
  history: { en: 'History & Progress', zh: '历史统计' },
  aiAdvisor: { en: 'AI Coach Advisor', zh: 'AI 智能教练' },
  askAi: { en: 'Ask for Advice', zh: '获取建议' },
  aiPromptPlaceholder: { en: 'Ask specifically about this member...', zh: '针对该会员提问...' },
  uploadPhoto: { en: 'Upload Progress Photo', zh: '上传体态照片' },
  studioName: { en: 'Studio Name', zh: '工作室名称' },
  save: { en: 'Save', zh: '保存' },
  cancel: { en: 'Cancel', zh: '取消' },
  edit: { en: 'Edit', zh: '修改' },
  delete: { en: 'Delete', zh: '删除' },
  loading: { en: 'Loading...', zh: '加载中...' },
  selectMember: { en: 'Select a member', zh: '请选择会员' },
  sessionDate: { en: 'Session Date', zh: '训练日期' },
  sessionPreview: { en: 'Session Preview', zh: '训练内容预览' },
  saveSession: { en: 'Save Full Session', zh: '保存本次训练' },
  remove: { en: 'Remove', zh: '移除' },
  filterMonth: { en: 'Filter Month', zh: '筛选月份' },
  noExercisesInSession: { en: 'No exercises added yet.', zh: '暂未添加动作' },
  chartMetric: { en: 'Metric', zh: '统计维度' },
  metricWeight: { en: 'Max Weight', zh: '绝对重量' },
  metricVolume: { en: 'Volume', zh: '训练容量' },
  selectExercises: { en: 'Select Exercises', zh: '选择动作' },
  calendar: { en: 'Training Calendar', zh: '训练日历' },
  viewDetails: { en: 'View Details', zh: '查看详情' },
  exercisesCompleted: { en: 'exercises', zh: '个动作' },
  close: { en: 'Close', zh: '关闭' },
  sessionDetails: { en: 'Session Details', zh: '训练详情' },
  newMemberName: { en: 'New Member Name', zh: '新会员姓名' },
  confirmDelete: { en: 'Are you sure you want to delete this?', zh: '确定要删除这条记录吗?' },
  memberExists: { en: 'Member with this name already exists!', zh: '该会员姓名已存在！' },
  exportData: { en: 'Export Data (xlsx)', zh: '导出记录 (xlsx)' },
  // 导航
  navDashboard: { en: 'Dashboard', zh: '仪表盘' },
  navPosture: { en: 'Posture Assessment', zh: '体态评估' },
  navReport: { en: 'Report Export', zh: '报告导出' },
  navSettings: { en: 'Settings', zh: '设置' },
  // 体态评估
  postureTitle: { en: 'Posture Assessment', zh: '体态评估' },
  frontPhoto: { en: 'Front Photo', zh: '正面照' },
  sidePhoto: { en: 'Side Photo', zh: '侧面照' },
  backPhoto: { en: 'Back Photo (Optional)', zh: '背面照（可选）' },
  heightCm: { en: 'Height (cm)', zh: '身高 (cm)' },
  gender: { en: 'Gender', zh: '性别' },
  male: { en: 'Male', zh: '男' },
  female: { en: 'Female', zh: '女' },
  startAnalysis: { en: 'Start Analysis', zh: '开始分析' },
  analyzing: { en: 'Analyzing...', zh: '分析中...' },
  detectingKeypoints: { en: 'Detecting keypoints...', zh: '正在检测关键点...' },
  postureScore: { en: 'Posture Score', zh: '综合体态评分' },
  detectionResults: { en: 'Detection Results', zh: '检测结果' },
  confidence: { en: 'Confidence', zh: '置信度' },
  changePhoto: { en: 'Change Photo', zh: '更换照片' },
  noAnalysisData: { en: 'No posture assessment data', zh: '暂无体态评估数据' },
  noCorrectionPlan: { en: 'No correction plan data', zh: '暂无矫正方案数据' },
  // 矫正方案
  correctionPlan: { en: '4-Week Correction Plan', zh: '4周矫正训练方案' },
  week1_2: { en: 'Week 1-2 (Activation)', zh: '第1-2周（放松激活）' },
  week3_4: { en: 'Week 3-4 (Integration)', zh: '第3-4周（强化整合）' },
  noExercisesPhase: { en: 'No exercises for this phase', zh: '暂无该阶段矫正动作' },
  // AI 配置
  aiConfig: { en: 'AI Config', zh: 'AI 配置' },
  aiProvider: { en: 'AI Provider', zh: 'AI 提供商' },
  apiKey: { en: 'API Key', zh: 'API Key' },
  baseUrl: { en: 'Base URL', zh: 'Base URL' },
  modelName: { en: 'Model Name', zh: '模型名称' },
  testConnection: { en: 'Test Connection', zh: '测试连接' },
  connectionSuccess: { en: 'Connection successful', zh: '连接成功' },
  connectionFailed: { en: 'Connection failed', zh: '连接失败' },
  enterApiKey: { en: 'Please enter API Key first', zh: '请先填写 API Key' },
  // 报告
  reportTitle: { en: 'Member Training Report', zh: '会员训练报告' },
  memberName: { en: 'Name', zh: '姓名' },
  joinDate: { en: 'Join Date', zh: '入会日期' },
  reportDate: { en: 'Report Date', zh: '报告日期' },
  monthlySessions: { en: 'Monthly Sessions', zh: '本月训练' },
  maxWeightPR: { en: 'Max Weight', zh: '最大重量' },
  totalVolumeLabel: { en: 'Total Volume', zh: '总容量' },
  volumeTrend: { en: 'Training Volume Trend (Last 6 Months)', zh: '训练容量趋势 (近6个月)' },
  sessions: { en: 'sessions', zh: '次' },
  postureAssessment: { en: 'Posture Assessment', zh: '体态评估' },
  aiRecommendations: { en: 'AI Recommendations', zh: 'AI 综合建议' },
  recentRecords: { en: 'Recent Training Records', zh: '近期训练记录' },
  noRecords: { en: 'No training records yet', zh: '暂无训练记录' },
  exportPDF: { en: 'Export PDF', zh: '导出 PDF' },
  generatingPDF: { en: 'Generating PDF...', zh: '正在生成 PDF...' },
  pageLabel: { en: 'Page', zh: '第' },
  reportPreviewTitle: { en: 'Report Preview', zh: '报告预览' },
  pageReportDesc: { en: 'page report | Training stats +', zh: '页报告 | 训练统计 +' },
  postureReportPart: { en: 'posture assessment + correction plan', zh: '体态评估 + 矫正方案' },
  workoutHistoryPart: { en: 'workout history', zh: '训练记录' },
  // 设置
  studioSettings: { en: 'Studio', zh: '工作室' },
  dataManagement: { en: 'Data', zh: '数据管理' },
  studioNameSetting: { en: 'Studio Name', zh: '工作室名称' },
  dataLocalNote: { en: 'All data is stored locally in IndexedDB. Clearing browser data will erase records.', zh: '所有数据存储在浏览器本地 IndexedDB 中。清除浏览器数据将丢失记录。' },
  exportJSON: { en: 'Export Data (JSON)', zh: '导出数据 (JSON)' },
  clearAllData: { en: 'Clear All Data', zh: '清除所有数据' },
  // 日期/表格
  dateCol: { en: 'Date', zh: '日期' },
  exerciseCol: { en: 'Exercise', zh: '动作' },
  weightCol: { en: 'Weight', zh: '重量' },
  setsRepsCol: { en: 'Sets x Reps', zh: '组 x 次' },
  volumeCol: { en: 'Volume', zh: '容量' },
  // 错误提示
  errorAnalysisFailed: { en: 'Analysis failed, please retry', zh: '分析失败，请重试' },
  errorServiceUnavailable: { en: 'Analysis service unavailable', zh: '分析服务不可用' },
  errorUploadMinPhotos: { en: 'Please upload at least front and side photos', zh: '请至少上传正面照和侧面照' },
  errorImageFormat: { en: 'Only JPEG / PNG format supported', zh: '仅支持 JPEG / PNG 格式' },
  errorImageSize: { en: 'Image size must be under 10MB', zh: '图片大小不能超过 10MB' },
  errorImageProcessing: { en: 'Image processing failed, please retry', zh: '图片处理失败，请重试' },
  errorPDFGeneration: { en: 'PDF generation failed', zh: 'PDF 生成失败' },
  // 体态问题严重度
  severityNormal: { en: 'Normal', zh: '正常' },
  severityModerate: { en: 'Moderate', zh: '中度' },
  severitySevere: { en: 'Severe', zh: '严重' },
  severityLowConfidence: { en: 'Low Confidence', zh: '低置信度' },
  // 体态问题名称双语（常见体态问题）
  postureIssueShoulderImbalance: { en: 'Shoulder Height Imbalance', zh: '高低肩' },
  postureIssueForwardHead: { en: 'Forward Head Posture', zh: '头前引' },
  postureIssueRoundedShoulders: { en: 'Rounded Shoulders', zh: '含胸圆肩' },
  postureIssuePelvicTilt: { en: 'Pelvic Tilt', zh: '骨盆倾斜' },
  postureIssueKneeValgus: { en: 'Knee Valgus', zh: '膝内扣' },
  postureIssueScoliosis: { en: 'Scoliosis', zh: '脊柱侧弯' },
  postureIssueUnevenHips: { en: 'Uneven Hips', zh: '骨盆高低' },
  postureIssueThoracicKyphosis: { en: 'Thoracic Kyphosis', zh: '胸椎后凸' },
  postureIssueLumbarLordosis: { en: 'Lumbar Lordosis', zh: '腰椎前凸' },
  postureIssueScapularWinging: { en: 'Scapular Winging', zh: '翼状肩胛' },
};

export const INITIAL_MEMBERS: Member[] = SEED_MEMBERS.map((s, idx) => ({
  id: String(idx + 1),
  name: s.name,
  avatar: s.avatar || `https://picsum.photos/200/200?random=${idx}`,
  joinDate: s.joinDate,
  gender: s.gender || 'male',
  heightCm: s.heightCm || 170,
  weightKg: s.weightKg,
  workouts: s.workouts.map((w, wIdx) => ({
    ...w,
    id: `${idx + 1}-${wIdx}`
  })),
  assessments: [],
}));
