import { TranslationDictionary, Member } from './types';
import { SEED_MEMBERS } from './services/seedData';

export const TRANSLATIONS: TranslationDictionary = {
  dashboard: { en: 'Dashboard', zh: '仪表盘' },
  members: { en: 'Members', zh: '会员列表' },
  addMember: { en: 'Add Member', zh: '添加会员' },
  deleteMember: { en: 'Delete', zh: '删除' },
  overview: { en: 'Overview', zh: '概览' },
  monthlyWorkouts: { en: 'Monthly Workouts', zh: '本月训练次数' },
  maxWeight: { en: 'Max Weight (PR)', zh: '最大重量突破' },
  totalVolume: { en: 'Total Volume', zh: '总训练容量' },
  logWorkout: { en: 'Log Workout Session', zh: '记录训练' },
  exercise: { en: 'Exercise', zh: '动作' },
  weight: { en: 'Weight', zh: '重量' },
  sets: { en: 'Sets', zh: '组' },
  reps: { en: 'Reps', zh: '次' },
  addLog: { en: 'Add to Session', zh: '加入训练单' },
  history: { en: 'History & Progress', zh: '历史统计' },
  aiAdvisor: { en: 'AI Coach Advisor', zh: 'AI 智能教练' },
  askAi: { en: 'Ask for Advice', zh: '获取建议' },
  aiPromptPlaceholder: { en: 'Ask specifically about this member...', zh: '针对该会员提问...' },
  uploadPhoto: { en: 'Upload Progress Photo', zh: '上传体态照片' },
  studioName: { en: 'Studio Name', zh: '工作室名称' },
  save: { en: 'Save', zh: '保存' },
  cancel: { en: 'Cancel', zh: '取消' },
  edit: { en: 'Edit', zh: '修改' },
  delete: { en: 'Delete', zh: '删除' },
  loading: { en: 'Loading...', zh: '加载中...' },
  selectMember: { en: 'Select a member', zh: '请选择会员' },
  sessionDate: { en: 'Session Date', zh: '训练日期' },
  sessionPreview: { en: 'Session Preview', zh: '训练内容预览' },
  saveSession: { en: 'Save Full Session', zh: '保存本次训练' },
  remove: { en: 'Remove', zh: '移除' },
  filterMonth: { en: 'Filter Month', zh: '筛选月份' },
  noExercisesInSession: { en: 'No exercises added yet.', zh: '暂未添加动作' },
  chartMetric: { en: 'Metric', zh: '统计维度' },
  metricWeight: { en: 'Max Weight', zh: '绝对重量' },
  metricVolume: { en: 'Volume', zh: '训练容量' },
  selectExercises: { en: 'Select Exercises', zh: '选择动作' },
  calendar: { en: 'Training Calendar', zh: '训练日历' },
  viewDetails: { en: 'View Details', zh: '查看详情' },
  exercisesCompleted: { en: 'exercises', zh: '个动作' },
  close: { en: 'Close', zh: '关闭' },
  sessionDetails: { en: 'Session Details', zh: '训练详情' },
  newMemberName: { en: 'New Member Name', zh: '新会员姓名' },
  confirmDelete: { en: 'Are you sure you want to delete this?', zh: '确定要删除这条记录吗?' },
  memberExists: { en: 'Member with this name already exists!', zh: '该会员姓名已存在！' },
  exportData: { en: 'Export Data (xlsx)', zh: '导出记录 (xlsx)' },
};

export const INITIAL_MEMBERS: Member[] = SEED_MEMBERS.map((s, idx) => ({
  id: String(idx + 1),
  name: s.name,
  avatar: s.avatar || `https://picsum.photos/200/200?random=${idx}`,
  joinDate: s.joinDate,
  workouts: s.workouts.map((w, wIdx) => ({
    ...w,
    id: `${idx + 1}-${wIdx}`
  }))
}));