import { TranslationDictionary, Member } from './types';

export const TRANSLATIONS: TranslationDictionary = {
  dashboard: { en: 'Dashboard', zh: '仪表盘' },
  members: { en: 'Members', zh: '会员列表' },
  addMember: { en: 'Add Member', zh: '添加会员' },
  deleteMember: { en: 'Delete', zh: '删除' },
  overview: { en: 'Overview', zh: '概览' },
  monthlyWorkouts: { en: 'Monthly Workouts', zh: '本月训练次数' },
  maxWeight: { en: 'Max Weight (PR)', zh: '最大重量突破' },
  totalVolume: { en: 'Total Volume', zh: '总训练容量' },
  logWorkout: { en: 'Log Workout Session', zh: '记录训练' },
  exercise: { en: 'Exercise', zh: '动作' },
  weight: { en: 'Weight', zh: '重量' },
  sets: { en: 'Sets', zh: '组' },
  reps: { en: 'Reps', zh: '次' },
  addLog: { en: 'Add to Session', zh: '加入训练单' },
  history: { en: 'History & Progress', zh: '历史统计' },
  aiAdvisor: { en: 'AI Coach Advisor', zh: 'AI 智能教练' },
  askAi: { en: 'Ask for Advice', zh: '获取建议' },
  aiPromptPlaceholder: { en: 'Ask specifically about this member...', zh: '针对该会员提问...' },
  uploadPhoto: { en: 'Upload Progress Photo', zh: '上传体态照片' },
  studioName: { en: 'Studio Name', zh: '工作室名称' },
  save: { en: 'Save', zh: '保存' },
  cancel: { en: 'Cancel', zh: '取消' },
  edit: { en: 'Edit', zh: '修改' },
  delete: { en: 'Delete', zh: '删除' },
  loading: { en: 'Loading...', zh: '加载中...' },
  selectMember: { en: 'Select a member', zh: '请选择会员' },
  sessionDate: { en: 'Session Date', zh: '训练日期' },
  sessionPreview: { en: 'Session Preview', zh: '训练内容预览' },
  saveSession: { en: 'Save Full Session', zh: '保存本次训练' },
  remove: { en: 'Remove', zh: '移除' },
  filterMonth: { en: 'Filter Month', zh: '筛选月份' },
  noExercisesInSession: { en: 'No exercises added yet.', zh: '暂未添加动作' },
  chartMetric: { en: 'Metric', zh: '统计维度' },
  metricWeight: { en: 'Max Weight', zh: '绝对重量' },
  metricVolume: { en: 'Volume', zh: '训练容量' },
  selectExercises: { en: 'Select Exercises', zh: '选择动作' },
  calendar: { en: 'Training Calendar', zh: '训练日历' },
  viewDetails: { en: 'View Details', zh: '查看详情' },
  exercisesCompleted: { en: 'exercises', zh: '个动作' },
  close: { en: 'Close', zh: '关闭' },
  sessionDetails: { en: 'Session Details', zh: '训练详情' },
  newMemberName: { en: 'New Member Name', zh: '新会员姓名' },
  confirmDelete: { en: 'Are you sure you want to delete this?', zh: '确定要删除这条记录吗?' },
  memberExists: { en: 'Member with this name already exists!', zh: '该会员姓名已存在！' },
  exportData: { en: 'Export Data (xlsx)', zh: '导出记录 (xlsx)' },
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: '1',
    name: 'Alice Chen',
    avatar: 'https://picsum.photos/200/200?random=1',
    joinDate: '2023-10-01',
    workouts: [
      { id: '101', date: '2023-10-05', exercise: 'Deadlift', weight: 60, sets: 3, reps: 5 },
      { id: '102', date: '2023-10-08', exercise: 'Squat', weight: 45, sets: 4, reps: 8 },
      { id: '103', date: '2023-10-12', exercise: 'Deadlift', weight: 65, sets: 3, reps: 5 },
      { id: '104', date: '2023-10-15', exercise: 'Bench Press', weight: 30, sets: 3, reps: 10 },
      { id: '105', date: '2023-10-20', exercise: 'Deadlift', weight: 70, sets: 3, reps: 3 },
      { id: '106', date: '2023-11-02', exercise: 'Squat', weight: 50, sets: 5, reps: 5 },
      { id: '107', date: '2023-11-02', exercise: 'Bench Press', weight: 32.5, sets: 3, reps: 8 },
    ],
  },
  {
    id: '2',
    name: 'Bob Smith',
    avatar: 'https://picsum.photos/200/200?random=2',
    joinDate: '2023-09-15',
    workouts: [
      { id: '201', date: '2023-09-16', exercise: 'Bench Press', weight: 80, sets: 5, reps: 5 },
      { id: '202', date: '2023-09-20', exercise: 'Squat', weight: 100, sets: 5, reps: 5 },
      { id: '203', date: '2023-10-25', exercise: 'Bench Press', weight: 82.5, sets: 5, reps: 5 },
      { id: '204', date: '2023-11-05', exercise: 'Overhead Press', weight: 40, sets: 4, reps: 8 },
    ],
  },
  {
    id: '3',
    name: 'David Liu',
    avatar: 'https://picsum.photos/200/200?random=3',
    joinDate: '2023-11-01',
    workouts: [
      { id: '301', date: '2023-11-01', exercise: 'Pull Up', weight: 0, sets: 4, reps: 8 },
      { id: '302', date: '2023-11-03', exercise: 'Barbell Row', weight: 60, sets: 4, reps: 10 },
    ],
  },
  {
    id: '4',
    name: 'Sarah Jones',
    avatar: 'https://picsum.photos/200/200?random=4',
    joinDate: '2023-08-20',
    workouts: [],
  },
];